### ISSUE TITLE
get dependencies for files with mix import and require not working

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit-javascript#39]
STR
touch a.js b.js c.js
```js
//a.js
var c = require('./c');
import b from './b';
```
you will get only c as dependency.
If you switch the imports order to be:
```js
//a.js
import b from './b';
var c = require('./c');
```
It will identify b only.

**Comment by davidfirst** [comment]
This was an old issue with files that mix ES6 syntax with plain javascript. It has been fixed a while ago.
I tested both cases above and both work as expected.
