### ISSUE TITLE
Had to pull this into VSC manually.

### ISSUE THREAD

**Issue by Kazamario** [teambit/bit-javascript#94]
Good Evening,

Just wanted to call out that I needed to pull this manually to try to use the bit IS.

**System Info:**

OS Name	Microsoft Windows 10 Pro
Version	10.0.17763 Build 17763
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DESKTOP-BPM4SSS
System Manufacturer	Micro-Star International Co., Ltd.
System Model	GX780R/GT780R/GT780DXR/GT783R
System Type	x64-based PC
System SKU	To be filled by O.E.M.
Processor	Intel(R) Core(TM) i7-2720QM CPU @ 2.20GHz, 2201 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. E1761IMS V3.0H, 11/18/2011
SMBIOS Version	2.7
Embedded Controller Version	255.255
BIOS Mode	Legacy
BaseBoard Manufacturer	Micro-Star International Co., Ltd.
BaseBoard Product	MS-1761
BaseBoard Version	To be filled by O.E.M.
Platform Role	Mobile
Secure Boot State	Unsupported
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.17763.194"
User Name	***
Time Zone	Central Standard Time
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	16.0 GB
Available Physical Memory	9.10 GB
Total Virtual Memory	18.9 GB
Available Virtual Memory	11.4 GB
Page File Space	2.88 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, DMA Protection
Virtualization-based security Services Configured	
Virtualization-based security Services Running	
Device Encryption Support	Reasons for failed automatic device encryption: TPM is not usable, PCR7 binding is not supported, Hardware Security Test Interface failed and device is not InstantGo, Un-allowed DMA capable bus/device(s) detected, TPM is not usable
A hypervisor has been detected. Features required for Hyper-V will not be displayed.	

Node MSI Installer Version: node-v10.15.1-x64

Maybe it's included in 11? ¯\_(ツ)_/¯

**Comment by davidfirst** [comment]
@Kazamario , I guess you posted in the wrong repo. Please re-open otherwise.
